name: HISTORY CLEAN UP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to gh-pages
        uses: actions/checkout@v3

      - name: Clean up
        run: |
          COUNT=$( ( ls | wc -l ) )
          echo "Total count = ${COUNT}"
          INPUT_KEEP_REPORTS=44
          echo "if ${COUNT} > ${INPUT_KEEP_REPORTS}"
          if (( ${COUNT} > ${INPUT_KEEP_REPORTS} )); then
            echo "Removing Old Reports"
            ls | grep -vE 'index.html|last-history' | sort -n | head -n -$((INPUT_KEEP_REPORTS-2)) | xargs rm -rv;
            cd ${GITHUB_WORKSPACE}
            git config user.email "action@github.com"
            git config user.name "GitHub Action"
            git status
            git add .
            git commit -m "Automated History Clean Up"
            git push origin gh-pages
          fi  
          ls
          
