name: HISTORY CLEAN UP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to gh-pages
        uses: actions/checkout@v3

      - name: Clean up
        run: |
          COUNT=$( ( ls | wc -l ) )
          echo "count folders in allure-history: ${COUNT}"
          echo "keep reports count 5"
          INPUT_KEEP_REPORTS=$((5+1))
          echo "if ${COUNT} > ${INPUT_KEEP_REPORTS}"
          if (( ${COUNT} > ${INPUT_KEEP_REPORTS} )); then
            ls
            echo "remove index.html last-history"
            rm index.html last-history -rv
            echo "remove old reports"
            ls | sort -n | head -n -$((5-2)) | xargs rm -rv;
            cd ${GITHUB_WORKSPACE}
          fi
          git add *
          git commit -m "clean up"
          git push
