name: Run Selenium On GitHub Action
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed

      - name: Check verion/path
        run: |
          google-chrome --version
          chromedriver --version
          readlink -f chromedriver

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Install Allure
        run: |
          wget -q https://github.com/allure-framework/allure2/releases/download/2.24.1/allure_2.24.1-1_all.deb
          sudo dpkg -i allure_2.24.1-1_all.deb

      - name: Running the Python script
        run: |
          pytest -m test_run -v -s --disable-warnings --alluredir=allure-results

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Report
        run: |
          mkdir -p ./allure-history
          cp -r ./gh-pages/. ./allure-history
          ls ./allure-history

          REPOSITORY_OWNER_SLASH_NAME=${{ github.repository }}
          REPOSITORY_NAME=${REPOSITORY_OWNER_SLASH_NAME##*/}
          GITHUB_PAGES_WEBSITE_URL="https://${{ github.repository_owner }}.github.io/${REPOSITORY_NAME}"
          echo "Github pages url $GITHUB_PAGES_WEBSITE_URL"

          echo "index.html"
          echo "<!DOCTYPE html><meta charset=\"utf-8\"><meta http-equiv=\"refresh\" content=\"0; URL=${GITHUB_PAGES_WEBSITE_URL}/${{ github.run_number }}/\">" > ./allure-history/index.html # path
          echo "<meta http-equiv=\"Pragma\" content=\"no-cache\"><meta http-equiv=\"Expires\" content=\"0\">" >> ./allure-history/index.html
          #cat ./allure-history/index.html

          #echo "executor.json"
          echo '{"name":"GitHub Actions","type":"github","reportName":"Allure Report with history",' > executor.json
          echo "\"url\":\"${GITHUB_PAGES_WEBSITE_URL}\"," >> executor.json # ???
          echo "\"reportUrl\":\"${GITHUB_PAGES_WEBSITE_URL}/${{ github.run_number }}/\"," >> executor.json
          echo "\"buildUrl\":\"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"," >> executor.json
          echo "\"buildName\":\"GitHub Actions Run #${{ github.run_id }}\",\"buildOrder\":\"${{ github.run_number }}\"}" >> executor.json
          #cat executor.json
          mv ./executor.json ./allure-results

          #environment.properties
          echo "URL=${GITHUB_PAGES_WEBSITE_URL}" >> ./allure-results/environment.properties
                      
          path="./gh-pages/last-history"  
          if [ -d "$path" ]; then
            echo "keep allure history from gh-pages/last-history to allure-results/history"
            cp -r ./gh-pages/last-history/. ./allure-results/history
          fi

          echo "generating report from allure-results to allure-report ..."
          allure generate --clean allure-results -o allure-report

          echo "copy allure-report to allure-history/${{ github.run_number }}"
          cp -r ./allure-report/. ./allure-history/${{ github.run_number }}
          echo "copy allure-report history to /allure-history/last-history"
          cp -r ./allure-report/history/. ./allure-history/last-history

      - name: Checking
        run: |
          cp -r allure-history/* gh-pages/
          cd gh-pages
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add *
          git commit -m "Deploy allure-history to gh-pages"
          git push origin gh-pages
