name: Run Selenium On GitHub Action
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed

      - name: Check verion/path
        run: |
          google-chrome --version
          chromedriver --version
          readlink -f chromedriver

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Install Allure
        run: |
          wget -q https://github.com/allure-framework/allure2/releases/download/2.24.1/allure_2.24.1-1_all.deb
          sudo dpkg -i allure_2.24.1-1_all.deb

      - name: Running the Python script
        run: |
          pytest -m test_run -v -s --disable-warnings --alluredir=allure-results
          ls
#          mkdir -p new-folder
#          cp -r allure-results/* new-folder

#      - name: Copy folder to destination
#        run: |
#          git fetch
#          git checkout gh-pages--
#          cp -r new-folder/* .
#          ls
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          git add new-folder
#          git commit -m "copied folder to source"
#          git push origin gh-pages
#        env:
#          destination-branch: gh-pages
#
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Check files
        run: |
          git rev-parse --abbrev-ref HEAD
          pwd
          ls
          cd gh-pages
          pwd
          ls
      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add allure-report
          git add allure-history
          git commit -m "Auto-commit by GitHub Actions"
          git remote add origin gh-pages
          git push
#
#      - uses: actions/checkout@v4
#        with:
#          clean: false
#      - run: |
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          git add ./allure-report
#          git commit -m "generated"
#          git push origin gh-pages --force

#      - name: Setup Pages
#        uses: actions/configure-pages@v2
#      - name: Upload artifact
#        uses: actions/upload-pages-artifact@v1
#        with:
#          # Upload entire repository
#          path: ./allure-report
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v1

#      - name: Deploy report to Github Pages
#        if: always()
#        uses: peaceiris/actions-gh-pages@v2
#        env:
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: allure-history
